package com.fleebug.corerouter.enums.activity;

public enum ActivityAction {
    CREATE_API_KEY,
    DEACTIVATE_API_KEY,
    DELETE_API_KEY,
    CHANGE_PASSWORD,
    UPDATE_PROFILE,
    SOFT_DELETE_ACCOUNT,
    WALLET_TOPUP_SUCCESS,
    ADMIN_MODEL_CREATED,
    ADMIN_MODEL_UPDATED,
    ADMIN_MODEL_DELETED,
    ADMIN_MODEL_STATUS_CHANGED,
    ADMIN_PROVIDER_CREATED,
    ADMIN_PROVIDER_UPDATED,
    ADMIN_PROVIDER_STATUS_CHANGED,
    ADMIN_PROVIDER_DELETED,
    ADMIN_SERVICE_TOKEN_CREATED,
    ADMIN_SERVICE_TOKEN_REVOKED,
    ADMIN_SERVICE_TOKEN_DELETED,
    LOGIN,
    LOGOUT
}
